local OWNER_ID = 4917748614 -- coloque aqui o seu UserId (so numeros)

return {
	FreeTesting = true,
	GamemodeSelection = true,
	NotAllowedKickMsg = "game currently shut down, will be back soon",
	FreeVIP = true,
	PreferCustomRankNames = false,
	UpdateLogOnce = true,
	DefaultAmbience = "rbxassetid://129991463413097",
	DefaultEmote = "rbxassetid://0",

	ManualRanks = {
		[4917748614] = 255,
	},

	CustomTitles = {
		[4917748614] = "[OWNER]",
	},
}
